import Head from 'next/head';

export default function Exam() {
  return (
    <div>
      <Head>
        <title>Exam Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Exam Board</div>
    </div>
  );
}
