import Head from 'next/head';
import Todo from './../../components/TodoPage/Todo';

export default function Exam() {
  return (
    <div>
      <Head>
        <title>Exam Board</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Todo />
    </div>
  );
}
