import { useEffect, useState } from 'react';

import DetailPage from './component/DetailPage';
import Form from '../create/components/Form';
import Head from 'next/head';
import studentApi from '../../api/studentService';

type EditProps = {
  data: any;
  id: string;
};
const DetailStudent = (props: EditProps) => {
  const { data, id } = props;
  return (
    <div>
      <Head>
        <title>Student Detail</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DetailPage data={data} />
    </div>
  );
};
DetailStudent.getInitialProps = async (ctx: any) => {
  const studentId = ctx.query.id;
  const res = await studentApi.getStudentById(studentId);
  return { data: res.data, id: studentId };
};
export default DetailStudent;
