import DetailPage from './component/DetailPage';
import Head from 'next/head';
import studentApi from '../../api/studentService';
import withPage from 'components/withPage';

type EditProps = {
  data: any;
  id: string;
};
const DetailStudent = (props: EditProps) => {
  const { data, id } = props;
  return (
    <>
      <Head>
        <title>Student Detail</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DetailPage data={data} />
    </>
  );
};
DetailStudent.getInitialProps = async (ctx: any) => {
  const studentId = ctx.query.id;
  const res = await studentApi.getStudentById(studentId);
  return { data: res.data, id: studentId };
};
export default withPage(DetailStudent);
