import Head from 'next/head';
import SignInPage from './sign-in/SignInPage';
import Todo from 'ui-components/TodoPage/Todo';

export default function Exam() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <SignInPage />
    </div>
  );
}
