import Head from 'next/head';
import Login from './components/LoginForm';

export default function Exam() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Login />
    </div>
  );
}
