import Head from 'next/head';

export default function Class() {
  return (
    <div>
      <Head>
        <title>Class Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Class Board</div>
    </div>
  );
}
