export enum studentAction {
  GET_ALL_STUDENT = 'GET_ALL_STUDENT',
  POPULATE_STUDENT = 'POPULATE_STUDENT',
  ADD_STUDENT = 'ADD_STUDENT',
  REMOVE_STUDENT = 'REMOVE_STUDENT',
  EDIT_STUDENT = 'EDIT_STUDENT',
}
