import { useEffect, useState } from 'react';

import Form from '../create/components/Form';
import Head from 'next/head';
import studentApi from '../../api/studentService';
import { useRouter } from 'next/router';
type EditProps = {
  data: any;
};
const EditPage = (props: EditProps) => {
  const { data } = props;
  console.log({ data });
  // const [student, setStudent] = useState<any>({});
  // useEffect(() => {
  //   const fetchStudentById = async () => {
  //     try {
  //       const response = await studentApi.getStudentById(studentId);
  //       setStudent(response.data);
  //     } catch (error) {
  //       console.log('Failed to fetch product list: ', error);
  //     }
  //   };
  //   fetchStudentById();
  // }, [studentId]);
  return (
    <div>
      <Head>
        <title>Edit Student</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Edit student - {2}</div>
      <Form data={data} isEdit={true} />
    </div>
  );
};
EditPage.getInitialProps = async (ctx: any) => {
  const studentId = ctx.query.id;
  const res = await studentApi.getStudentById(studentId);
  console.log({ res });
  return { data: res.data };
};
export default EditPage;
