import { Form } from 'antd';
import Head from 'next/head';
import studentApi from '../../api/studentService';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function EditPage() {
  const router = useRouter();
  const studentId = router.query.id;
  console.log({ studentId });
  useEffect(() => {
    const fetchStudentById = async () => {
      try {
        const response = await studentApi.getStudentById(studentId);
        console.log({ response });
      } catch (error) {
        console.log('Failed to fetch product list: ', error);
      }
    };
    fetchStudentById();
  }, [studentId]);
  return (
    <div>
      <Head>
        <title>Edit Student</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Edit student - {studentId}</div>
      <Form />
    </div>
  );
}
