import '../styles/globals.css';

import type { AppProps } from 'next/app';
import { Box } from '../ui/General/Box';
import Head from 'next/head';
import Nav from '../ui/Navigation/Nav';
import { wrapper } from '../store/store';

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="stylesheet" href="/styles/globals.css" /> */}
      </Head>
      <Box style={{ display: 'flex' }}>
        <Nav />
        <Box style={{ width: '100%' }}>
          <Component {...pageProps} />
        </Box>
      </Box>
    </>
  );
};
export default wrapper.withRedux(App);
