import '../styles/globals.css';

import type { AppProps } from 'next/app';
import { Box } from 'ui-components/General/Box';
import Footer from 'ui-components/Footer/Footer';
import Head from 'next/head';
import MenuBar from 'ui-components/Navigation/MenuBar';
import { wrapper } from '../redux/store/store';

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/styles/globals.css" />
      </Head>

      <MenuBar />
      <Box
        position="relative"
        paddingTop="103px"
        w="100%"
        minHeight="calc(100vh - 295px)"
      >
        <Component {...pageProps} />
      </Box>
      <Footer />
    </>
  );
};
export default wrapper.withRedux(App);
