import Head from 'next/head';
import Todo from 'ui-components/TodoPage/Todo';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Todo />
    </div>
  );
}
