import { useEffect, useState } from 'react';

import Head from 'next/head';
import axios from 'axios';
import studentApi from './api/studentService';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [productList, setProductList] = useState([]);
  useEffect(() => {
    const fetchProductList = async () => {
      try {
        const response = await studentApi.getAll();
        console.log('Fetch products successfully', { response });
      } catch (error) {
        console.log('Failed to fetch product list: ', error);
      }
    };
    fetchProductList();
  }, []);
  console.log({ productList });
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>Home Page</div>
    </div>
  );
}
