import Head from 'next/head';
import List from './components/List';

export default function User() {
  return (
    <div>
      <Head>
        <title>Student List Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <List />
    </div>
  );
}
